\NeedsTeXFormat{LaTeX2e}
\ProvidesPackage{ReflectionsDoc.cls}
\LoadClass[12pt]{article}
\RequirePackage[left=2cm, right=2cm, bottom=3cm]{geometry}
\RequirePackage[scaled]{helvet}
\RequirePackage[parfill]{parskip}
\RequirePackage[T1]{fontenc}
\RequirePackage{fancyhdr}
\RequirePackage{lipsum}
\RequirePackage{color}
\RequirePackage{microtype}
\renewcommand\familydefault{\sfdefault}
\lhead{Reflection document}
\rhead{Ivan Barinskiy}
\setlength{\headheight}{15pt} % hides warning
\pagestyle{fancy}
\setcounter{secnumdepth}{0}
